### ISSUE TITLE
[typeorm0.3-custom_repository] Dependency Injection 문제가 있습니다.

### ISSUE THREAD

**Issue by rollrat** [hou27/nestjs-examples#1]
```
PS C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository> npm start dev

> typeorm0.3-custom-repository@0.0.1 start
> nest start "dev"

[Nest] 3576  - 2022. 10. 09. 오후 3:31:30     LOG [NestFactory] Starting Nest application...
[Nest] 3576  - 2022. 10. 09. 오후 3:31:30     LOG [InstanceLoader] AppModule dependencies initialized +70ms
[Nest] 3576  - 2022. 10. 09. 오후 3:31:30     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 3576  - 2022. 10. 09. 오후 3:31:30   ERROR [ExceptionHandler] Nest can't resolve dependencies of the UsersService (?). Please make sure that the argument Object at index [0] is available in the UsersModule context.

Potential solutions:
- If Object is a provider, is it part of the current UsersModule?
- If Object is exported from a separate @Module, is that module imported within UsersModule?
  @Module({
    imports: [ /* the Module containing Object */ ]
  })

Error: Nest can't resolve dependencies of the UsersService (?). Please make sure that the argument Object at index [0] is available in the UsersModule context.

Potential solutions:
- If Object is a provider, is it part of the current UsersModule?
- If Object is exported from a separate @Module, is that module imported within UsersModule?
  @Module({
    imports: [ /* the Module containing Object */ ]
  })

    at Injector.lookupComponentInParentModules (C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository\node_modules\@nestjs\core\injector\injector.js:241:19)
    at Injector.resolveComponentInstance (C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository\node_modules\@nestjs\core\injector\injector.js:194:33)
    at resolveParam (C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository\node_modules\@nestjs\core\injector\injector.js:116:38)
    at async Promise.all (index 0)
    at Injector.resolveConstructorParams (C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository\node_modules\@nestjs\core\injector\injector.js:131:27)
    at Injector.loadInstance (C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository\node_modules\@nestjs\core\injector\injector.js:57:13)
    at Injector.loadProvider (C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository\node_modules\@nestjs\core\injector\injector.js:84:9)
    at async Promise.all (index 4)
    at InstanceLoader.createInstancesOfProviders (C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository\node_modules\@nestjs\core\injector\instance-loader.js:44:9)
    at C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository\node_modules\@nestjs\core\injector\instance-loader.js:29:13
```

비슷한 방법으로 구현한 코드를 찾을 수가 없어서 이슈 남깁니다

**Comment by hou27** [comment]
> ```
> PS C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository> npm start dev
> 
> > typeorm0.3-custom-repository@0.0.1 start
> > nest start "dev"
> 
> [Nest] 3576  - 2022. 10. 09. 오후 3:31:30     LOG [NestFactory] Starting Nest application...
> [Nest] 3576  - 2022. 10. 09. 오후 3:31:30     LOG [InstanceLoader] AppModule dependencies initialized +70ms
> [Nest] 3576  - 2022. 10. 09. 오후 3:31:30     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
> [Nest] 3576  - 2022. 10. 09. 오후 3:31:30   ERROR [ExceptionHandler] Nest can't resolve dependencies of the UsersService (?). Please make sure that the argument Object at index [0] is available in the UsersModule context.
> 
> Potential solutions:
> - If Object is a provider, is it part of the current UsersModule?
> - If Object is exported from a separate @Module, is that module imported within UsersModule?
>   @Module({
>     imports: [ /* the Module containing Object */ ]
>   })
> 
> Error: Nest can't resolve dependencies of the UsersService (?). Please make sure that the argument Object at index [0] is available in the UsersModule context.
> 
> Potential solutions:
> - If Object is a provider, is it part of the current UsersModule?
> - If Object is exported from a separate @Module, is that module imported within UsersModule?
>   @Module({
>     imports: [ /* the Module containing Object */ ]
>   })
> 
>     at Injector.lookupComponentInParentModules (C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository\node_modules\@nestjs\core\injector\injector.js:241:19)
>     at Injector.resolveComponentInstance (C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository\node_modules\@nestjs\core\injector\injector.js:194:33)
>     at resolveParam (C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository\node_modules\@nestjs\core\injector\injector.js:116:38)
>     at async Promise.all (index 0)
>     at Injector.resolveConstructorParams (C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository\node_modules\@nestjs\core\injector\injector.js:131:27)
>     at Injector.loadInstance (C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository\node_modules\@nestjs\core\injector\injector.js:57:13)
>     at Injector.loadProvider (C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository\node_modules\@nestjs\core\injector\injector.js:84:9)
>     at async Promise.all (index 4)
>     at InstanceLoader.createInstancesOfProviders (C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository\node_modules\@nestjs\core\injector\instance-loader.js:44:9)
>     at C:\Users\rollrat\Desktop\새 폴더\nestjs-examples-main\typeorm0.3-custom_repository\node_modules\@nestjs\core\injector\instance-loader.js:29:13
> ```
> 
> 비슷한 방법으로 구현한 코드를 찾을 수가 없어서 이슈 남깁니다

안녕하세요 우선 제 코드에 관심가져주셔서 감사합니다 ㅎ
저 또한 다른 분의 코드를 참고하여 공부하며 작성한 코드로, 테스트를 정확히 진행하지 않고 올려두어
테스트를 진행하심에 있어서 혼란을 드린 점 죄송합니다.

기본적으로 이 방법은 기존의 repository를 오버라이딩하고, 오버라이딩 된 커스텀 repository를 사용할 수 있도록 하는 것인데,
service에서 주입받아 사용하는 과정에서 NestJS가 인식하여 forFeature에 등록된 repository를 주입해줄 수 있도록 @InjectRepository()를 추가해야했으나, 이 부분이 누락되어 의존성 주입 에러가 발생됐었습니다.

[rollrat](https://github.com/rollrat)님 덕분에 에러를 수정할 수 있었습니다. 감사합니다.

**Comment by rollrat** [comment]
감사합니다!
